baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 15

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    languageName = "English"
    title = "Yasser Rachid"
    subtitle = "Notes"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "yrachid's notes"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/yrachid"
