#!/bin/bash -eu

init_routine() {
  git submodule init
  git submodule update
}

deploy_routine() {
  init_routine

  rm -rf public/
  mkdir public
  cp now.json public/

  hugo -v
  ls -la public/

  now public/
  now alias
}


run_routine() {
  init_routine
  hugo server --buildDrafts
}

post_routine() {
  local post_title=$1
  hugo new posts/${post_title}.md
}

case ${1:-none} in
  run)
    run_routine
    ;;

  post)
    post_routine "$2"
    ;;

  deploy)
    deploy_routine
    ;;

  *)
    echo
    echo "Available options: run, post, deploy"
    echo -e "\tpost receives the post title as param and runs hugo new posts/{post-title}.md"
    echo
    ;;
esac
